[package]
name = "jat"
version = "0.1.0"
authors = ["chlins <chlins.zhang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored_json = "2"
serde_json = "1.0"
